### ISSUE TITLE
helics-shared library not found

### ISSUE THREAD

**Issue by Dx-Wang** [GMLC-TDC/helics-ns3#32]
After installing HELICS, I have `libhelicsSharedLib.so` under the `lib` directory. However, the `wscript` search for `helics-shared`, which will cause a configuration error. Should I change `helics-shared` to `helicsSharedLib` in `wscript`? Or is there anything wrong with my HELICS installation? Thanks!

**Comment by nightlark** [comment]
`helics-shared` is the C++ shared library which requires building HELICS from source with the option enabled and provides a easier to use API than the `helicsSharedLib`, which is the C shared library. The [develop branch README](https://github.com/GMLC-TDC/helics-ns3/tree/develop) says what option is needed to build the C++ shared library. To avoid breaking existing 2.x programs, the naming will need to stay the same, but for HELICS 3.0 the naming is likely to change to something like `helics-shared-cxx` to make it clearer that it is a C++ shared library.

Unfortunately, distributing a precompiled C++ shared library is impractical because symbols/library ABI can depend on specific compiler versions, which makes for a very big build matrix (and challenges getting new compilers installed on an old version of Linux for portability).

**Comment by nightlark** [comment]
The main branch has now been updated with the README changes from develop.

**Comment by Dx-Wang** [comment]
So it is better to enable the option to build and use the C++ shared library. Thank you for the explanation.
